config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from sport_chat.chats.urls import api_urlpatterns
from sport_chat.users.views import FacebookLogin

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    url(r'^chat/$', TemplateView.as_view(template_name='chats/chat.html'), name='chat'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    
    url(r'^users/', include('sport_chat.users.urls', namespace='users')),
    # Your stuff: custom urls includes go here

    url(r'^chats/', include('sport_chat.chats.urls', namespace='chats')),

    url(r'^api/v1/', include(api_urlpatterns, namespace='api_v1')),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^rest-auth/facebook/$', FacebookLogin.as_view(), name='fb_login')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
            url(r'^channels-api/', include('channels_api.urls'))
        ] + urlpatterns

sport_chat/chats/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views
from . import apis

urlpatterns = [

    url(
        regex="^event/~create/$",
        view=views.EventCreateView.as_view(),
        name='event_create',
    ),
    url(
        regex="^event/(?P<pk>\d+)/~delete/$",
        view=views.EventDeleteView.as_view(),
        name='event_delete',
    ),
    url(
        regex="^event/(?P<pk>\d+)/$",
        view=views.EventDetailView.as_view(),
        name='event_detail',
    ),
    url(
        regex="^event/(?P<pk>\d+)/~update/$",
        view=views.EventUpdateView.as_view(),
        name='event_update',
    ),
    url(
        regex="^event/$",
        view=views.EventListView.as_view(),
        name='event_list',
    ),

    url(
        regex="^team/~create/$",
        view=views.TeamCreateView.as_view(),
        name='team_create',
    ),
    url(
        regex="^team/(?P<pk>\d+)/~delete/$",
        view=views.TeamDeleteView.as_view(),
        name='team_delete',
    ),
    url(
        regex="^team/(?P<pk>\d+)/$",
        view=views.TeamDetailView.as_view(),
        name='team_detail',
    ),
    url(
        regex="^team_chat/(?P<pk>\d+)/$",
        view=views.TeamChatDetailView.as_view(),
        name='team_chat_detail',
    ),
    url(
        regex="^team/(?P<pk>\d+)/~update/$",
        view=views.TeamUpdateView.as_view(),
        name='team_update',
    ),
    url(
        regex="^team/$",
        view=views.TeamListView.as_view(),
        name='team_list',
    ),

    url(
        regex="^notification/~create/$",
        view=views.NotificationCreateView.as_view(),
        name='notification_create',
    ),
    url(
        regex="^notification/(?P<pk>\d+)/~delete/$",
        view=views.NotificationDeleteView.as_view(),
        name='notification_delete',
    ),
    url(
        regex="^notification/(?P<pk>\d+)/$",
        view=views.NotificationDetailView.as_view(),
        name='notification_detail',
    ),
    url(
        regex="^notification/(?P<pk>\d+)/~update/$",
        view=views.NotificationUpdateView.as_view(),
        name='notification_update',
    ),
    url(
        regex="^notification/$",
        view=views.NotificationListView.as_view(),
        name='notification_list',
    ),

]

from sport_chat.users.views import token_auth


api_urlpatterns = [
    url(
        regex="^events/$",
        view=apis.EventListApiView.as_view(),
        name='event_list',
    ),
    url(
        regex="^events/(?P<pk>\d+)/$",
        view=apis.EventDetailApiView.as_view(),
        name='event_detail',
    ),
    url(
        regex="^events/(?P<pk>\d+)/messages/$",
        view=apis.EventMessageListApiView.as_view(),
        name='event_messages_list',
    ),
    url(
        regex = "^token/(?P<key>[^/]+)/$", 
        view = apis.TokenDetailApiView.as_view(), 
        name = "token_detail",
    ),
]

sport_chat/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

sport_chat/chats/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from image_cropping import ImageRatioField
from django.core.urlresolvers import reverse
from model_utils import Choices, FieldTracker
from django.utils.translation import ugettext_lazy as _
from model_utils.fields import StatusField, MonitorField
from django.utils.encoding import python_2_unicode_compatible
from model_utils.models import TimeStampedModel, SoftDeletableModel
from channels import Group

from .settings import MSG_TYPE_MESSAGE, MESSAGE_TYPES_CHOICES
import ujson as json
from .signals import create_message

from django.core.exceptions import ValidationError
from django.db.models import Q

from django.contrib.postgres.fields import JSONField


def team_flag_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/team_<name>/<filename>
    return 'team_{0}/{1}'.format(instance.name, filename)


@python_2_unicode_compatible
class Base(SoftDeletableModel, TimeStampedModel):
	
	tracker = FieldTracker()

	class Meta:
		abstract = True


@python_2_unicode_compatible
class Team(Base):

	name = models.CharField(
		max_length=55,
		verbose_name = _('Name of team'),
		)
	flag = models.ImageField(upload_to=team_flag_directory_path)
	cropping = ImageRatioField('flag', '430x360')


	def __str__(self):
		return self.name


@python_2_unicode_compatible
class Event(Base):

	STATUS = Choices(
		('soon', 'soon', _('Soon')), 
		('online', 'online', _('Online')),
		('end', 'end', _('End'))
	)

	status = models.CharField(
		choices=STATUS, 
		default=STATUS.soon,
		max_length=20
	)
	name = models.CharField(
		max_length=55,
		verbose_name = _('Name of event'),
		)
	home_team = models.ForeignKey(
		Team,
		related_name = 'event_home_team',
		verbose_name = _('Left team'),
		null=True,
		blank=False
		)
	away_team = models.ForeignKey(
		Team,
		related_name = 'event_away_team',
		verbose_name = _('Right team'),
		null=True,
		blank=False
		)
	start_date = models.DateTimeField(
		verbose_name = _('Start date and time'),
		help_text = _('Date and time when the event should start')
		)
	end_date = models.DateTimeField(
		verbose_name = _('End date and time'),
		help_text = _('Date and time when the event should end')
		)

	started_at = MonitorField(
		monitor='status', 
		when=['online']
	)
	ended_at = MonitorField(
		monitor='status', 
		when=['end']
	)
	users = models.ManyToManyField(
		settings.AUTH_USER_MODEL, 
		blank=False
	)
	data = JSONField(
		default={},
		null=True, 
		blank=False
	)

	def __str__(self):
		return self.name

	def clean(self):
		event = Event.objects.exclude(
			Q(status='end'),
		).filter(
			Q(home_team=self.home_team, away_team=self.away_team) | 
			Q(home_team=self.away_team, away_team=self.home_team) |
			Q(home_team=self.home_team) | Q(home_team=self.away_team) |
			Q(away_team=self.home_team) | Q(away_team=self.away_team)
		).exists()
		if event:
			raise ValidationError(_('You must end the event with these commands before you start a new one.'))

		if self.home_team == self.away_team:
			raise ValidationError(_('You must end the event with these commands before you start a new one.'))


		if self.start_date > self.end_date:
			raise ValidationError(_('Start date can not be longer than end date.'))


	@property
	def websocket_group(self):
	    """
	    Returns the Channels Group that sockets should subscribe to to get sent
	    messages as they are generated.
	    """
	    return Group("room-%s" % self.id)

	def add_to_room(self, user, team_id, team_name, team_align):
		if not user in self.users.all():
			self.users.add(user)
			self.data[user.username] = {'team_id': team_id, 'team_name': team_name, 'team_align': team_align}
			self.save()

	def leave_from_room(self, user, team_name, team_align):
		if user in self.users.all():
			self.users.delete(user)
			del self.data[user.username]
			self.save()

	def send_message(self, message, user, team_id=None, team_align=None, team_name=None, msg_type=MSG_TYPE_MESSAGE):
		"""
		Called to send a message to the room on behalf of a user.
		"""
		final_msg = {
			'room_id': str(self.id), 'message': message, 'username': user.username, 'team_id': team_id, 
			'team_name': team_name, 'msg_type': msg_type, "timestamp": timezone.now().strftime('%I:%M:%S %p'),
			'team_align': team_align
		}
		
		# Send signal for create new message
		create_message.send(
			sender=self.__class__, user=user, team=team_id, event=self.id, 
			message=message, msg_type=msg_type, team_type=team_align
			)

		# Send out the message to everyone in the room
		self.websocket_group.send(
		    {"text": json.dumps(final_msg)}
		)


@python_2_unicode_compatible
class Notification(Base):

	event = models.ForeignKey(
		Event
	)
	message = models.CharField(
		max_length=255
	)
	every = models.PositiveSmallIntegerField(
		default=0,
		verbose_name = _('Every'),
		help_text = _('The message will be sent each N number of minutes')
		)

	def __str__(self):
		return '{}'.format(self.pk)


@python_2_unicode_compatible
class Message(Base):

	TEAM_TYPES = Choices(
		('home', 'home', _('Home')), 
		('away', 'away', _('Away')),
	)
	event = models.ForeignKey(
		Event,
		related_name='event_messages'
	)
	team = models.ForeignKey(
		Team,
		related_name='team_messages',
		null=True,
	)
	msg_type = models.PositiveSmallIntegerField(
		choices=MESSAGE_TYPES_CHOICES,
		default=MESSAGE_TYPES_CHOICES[0][0],
	)
	team_type = models.CharField(
		choices=TEAM_TYPES, 
		default=TEAM_TYPES.home,
		max_length=4
	)
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	timestamp = models.DateTimeField(db_index=True, default=timezone.now)
	message = models.TextField()

	@property
	def human_timestamp(self):
		return self.timestamp.strftime('%I:%M:%S %p')

	def __str__(self):
		return '{0} at {1}'.format(self.user, self.timestamp)

sport_chat/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

sport_chat/chats/views.py
# -*- coding: utf-8 -*-
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    UpdateView,
    ListView,
    RedirectView,
)

from .models import (
    Team,
    Event,
    Notification,
    Message
)

from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin


class TeamCreateView(LoginRequiredMixin, CreateView):

    model = Team
    fields = '__all__'


class TeamDeleteView(LoginRequiredMixin, DeleteView):

    model = Team


class TeamDetailView(LoginRequiredMixin, DetailView):

    model = Team


class TeamChatDetailView(LoginRequiredMixin, DetailView):

    model = Team
    template_name = 'chats/team_chat.html'

    def get_context_data(self, *args, **kwargs):
        context = super(TeamChatDetailView, self).get_context_data(*args, **kwargs)
        event = Event.objects.exclude(
            Q(status='end'),
            Q(team_left=self.object) | Q(team_right=self.object)
        )
        #print(event)
        if event:
            context['event'] = event[0].pk
        context['chat_messages'] = Message.objects.filter(event=event)
        return context


class TeamUpdateView(LoginRequiredMixin, UpdateView):

    model = Team


class TeamListView(LoginRequiredMixin, ListView):

    model = Team


class EventCreateView(LoginRequiredMixin, CreateView):

    model = Event
    fields = '__all__'


class EventDeleteView(LoginRequiredMixin, DeleteView):

    model = Event


class EventDetailView(LoginRequiredMixin, DetailView):

    model = Event


class EventUpdateView(LoginRequiredMixin, UpdateView):

    model = Event


class EventListView(LoginRequiredMixin, ListView):

    model = Event

    def get_queryset(self):
        queryset = super(EventListView).get_queryset()
        return queryset.exclude(status='end')


class NotificationCreateView(LoginRequiredMixin, CreateView):

    model = Notification
    fields = '__all__'


class NotificationDeleteView(LoginRequiredMixin, DeleteView):

    model = Notification


class NotificationDetailView(LoginRequiredMixin, DetailView):

    model = Notification


class NotificationUpdateView(LoginRequiredMixin, UpdateView):

    model = Notification


class NotificationListView(LoginRequiredMixin, ListView):

    model = Notification

sport_chat/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
from rest_auth.registration.views import SocialLoginView

class FacebookLogin(SocialLoginView):
    adapter_class = FacebookOAuth2Adapter





from rest_framework.authtoken.models import Token 
from django.contrib.auth import authenticate, login
from django.core import serializers
from django.shortcuts import get_object_or_404

from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response


@api_view(['GET'])
def token_auth(request, token):
    try:
        token = Token.objects.get(key=token)
        user = authenticate(
            username = token.user.username,
            password = token.user.password
            )
        login(request, token.user, backend='allauth.account.auth_backends.AuthenticationBackend')
    except Token.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    return Response(status=status.HTTP_200_OK)

sport_chat/templates/chats/event_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Event: {{ object.name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.name }}</h2>
      <a href="{% url 'chats:team_chat_detail' object.team_left.pk %}"><h3 class="room">Join to {{ object.team_left }} team chat</h3></a>
      <a href="{% url 'chats:team_chat_detail' object.team_right.pk %}"><h3 class="room">Join to {{ object.team_right }} team chat</h3></a>
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

sport_chat/templates/chats/event_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create new event{% endblock %}

{% block content %}
  <h1>Create new event</h1>
  <form class="form-horizontal" method="post" action="{% url 'chats:event_create' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Create</button>
      </div>
    </div>
  </form>
{% endblock %}

sport_chat/templates/chats/event_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Events{% endblock %}

{% block content %}
<div class="container">
  <h2>Events</h2>

  <div class="list-group">
    {% for event in event_list %}
      <a href="{% url 'chats:event_detail' event.pk %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ event.name }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}

sport_chat/templates/chats/team_chat.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row">
<div class="col-md-12">
<h4>Hello <span class="username">{{ user.username }}</span>! You are joined to <span class="team">{{ object.name }}</span></h4>
</div>
</div>
<div class="row">
<div class="chat">
{% for chat_message in chat_messages %}
	<div class="{% if message.room == object.pk %} col-lg-8 {% else %} col-lg-4 col-lg-offset-4 {% endif %} message"> 
		<span style="color: blue">{{ chat_message.team.name }}</span> 
		<span style="color: red">{{ chat_message.user.username }}</span>
		{{ chat_message.content }}
		<span class="timestamp">{{ chat_message.timestamp }}</span>
	</div>
{% endfor %}
</div>
</div>
<div class="row">
<div class="col-md-12">
<input type="text" class="text">
<button class="btn send">Send</button>
</div>
</div>
{% endblock content %}

{% block include_javascript %}
<script type="text/javascript">
	var notificationRoom = {{ event }}
	var room = {{ object.pk }};
	var username = $('.username').text();
	var team = $('.team').text();
</script>
<script src="{% static 'js/ws.js' %}"></script>
<script type="text/javascript">
	$(document).ready(function(){
		var n = $(document).height();
		$('html, body').animate({ scrollTop: n }, 50);
		sendMessage = function(){
			var n = $(document).height();
			var text = $('.text').val();
			if ($.trim(text) !== '') {
				chat_socket.send(text);
			};
			$('.text').val('');
			$('html, body').animate({ scrollTop: n }, 50);
		};

		$(document).keypress(function(e) {
		    if(e.which == 13) {
		        sendMessage();
		    }
		});

		$('.send').click(function(){
			sendMessage();
		});
	});
</script>
{% endblock include_javascript %}

sport_chat/templates/chats/team_detail.html
{% extends 'base.html' %}

{% block content %}
{% endblock content %}

sport_chat/templates/chats/team_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Team new event{% endblock %}

{% block content %}
  <h1>Team new event</h1>
  <form class="form-horizontal" method="post" action="{% url 'chats:team_create' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Create</button>
      </div>
    </div>
  </form>
{% endblock %}

sport_chat/templates/chats/team_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Teams{% endblock %}

{% block content %}
<div class="container">
  <h2>Teams</h2>

  <div class="list-group">
    {% for team in team_list %}
      <a href="{% url 'chats:team_detail' team.pk %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ team.name }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}